<?php
include_once("Classes/Model/DB.Class.php");
include_once("Classes/Model/Doctors.Class.php");
include_once("Classes/Model/Patients.Class.php");
//include_once("Classes/Model/Reserves.Class.php");
include_once("Classes/Model/Comments.Class.php");
include_once("Classes/Model/Appointments.Class.php");
include_once("Classes/Model/ProfileImage.Class.php");
include_once("Classes/Model/ResetPassword.Class.php");
//include_once("Classes/Model/AppointmentReserve.Class.php");
include_once("Classes/Controller/DoctorsController.Class.php");
include_once("Classes/Controller/PatientsController.Class.php");
//include_once("Classes/Controller/ReservesController.Class.php");
include_once("Classes/Controller/CommentsController.Class.php");
include_once("Classes/Controller/AppointmentController.Class.php");
include_once("Classes/Controller/ProfileImageController.Class.php");
//include_once("Classes/Controller/ReservesController.Class.php");
include_once("Classes/Controller/ResetPasswordController.class.php");
include_once("Classes/View/AppointmentsView.Class.php");
include_once("Classes/View/CommentsView.Class.php");
include_once("Classes/View/DoctorsView.Class.php");
include_once("Classes/View/PatientsView.Class.php");
include_once("Classes/View/ProfileImageView.Class.php");
include_once("Classes/View/ResetPasswordView.class.php");
include_once("Classes/Message.Class.php");
include_once('Functions/Appointments.Function.php');
include_once('Functions/Authemtication.Function.php');
include_once('Functions/Doctors.Fucntion.php');
 ?>